### ISSUE TITLE
Release Checklist (v1.69.0)

### ISSUE THREAD

**Issue by amwolff** [storj/edge#388]
# Revision v1.69.0

```[tasklist]
## Release Requirements
- [x] Prepare Config Changes if Needed
- [x] Follow the steps in [MAINTAINERS.md.](https://github.com/storj/edge/blob/main/MAINTAINERS.md)
- [x] Run UI-based tests (below)
- [ ] https://github.com/storj/infra/pull/5342
```

```[tasklist]
### UI-based tests
- [x] verify upload functionality (text file, image file, video file)
- [x] verify download functionality (text file, image file, video file)
- [x] verify file preview (text file, image file, video file)
- [x] generate linkharing link and verify download functionality via alternate browser session
- [x] check folder sharing (below)
- [x] static web hosting using custom url with tls
```

```[tasklist]
#### Folder sharing tests
- [x] create "subfolder" (`demo/111/222`) and share access to it (give access to `…/222`)
- [x] check there's no access to root "folders" and data in them
```

## Comments
> As part of this release we had to manually run the job for building binaries and publishing docker images. They did not get generated as part of the tag creation as it had in previous releases. At this time we are not concerned or investigating the issue until we experience further issues. 

## Open Issues/Regressions
> None at this time.
