### ISSUE TITLE
Release Checklist (v1.70.2)

### ISSUE THREAD

**Issue by amwolff** [storj/edge#390]
# Revision v1.70.0

```[tasklist]
## Release Requirements
- [x] Prepare Config Changes if Needed
- [x] Follow the steps in [MAINTAINERS.md.](https://github.com/storj/edge/blob/main/MAINTAINERS.md)
- [x] Run UI-based tests (below)
```

```[tasklist]
### UI-based tests
- [x] verify upload functionality (text file, image file, video file)
- [x] verify download functionality (text file, image file, video file)
- [x] verify file preview (text file, image file, video file)
- [x] generate linksharing link and verify download functionality via alternate browser session
- [x] check folder sharing (below)
- [x] static web hosting using custom url with tls
```

```[tasklist]
#### Folder sharing tests
- [x] create "subfolder" (`demo/111/222`) and share access to it (give access to `…/222`)
- [x] check there's no access to root "folders" and data in them
```

## Comments
>No additional comments at this time.

## Open Issues/Regressions
> None at this time.
