### ISSUE TITLE
Release Checklist (v1.71.0)

### ISSUE THREAD

**Issue by amwolff** [storj/edge#393]
# Revision v1.71.0

```[tasklist]
## Release Requirements
- [x] Prepare Config Changes if Needed
- [x] Follow the steps in [MAINTAINERS.md.](https://github.com/storj/edge/blob/main/MAINTAINERS.md)
- [x] Run UI-based tests (below)
```

```[tasklist]
### UI-based tests
- [x] verify upload functionality (text file, image file, video file)
- [x] verify download functionality (text file, image file, video file)
- [x] verify file preview (text file, image file, video file)
- [x] generate linksharing link and verify download functionality via alternate browser session
- [x] check folder sharing (below)
```

```[tasklist]
#### Folder sharing tests
- [x] create "subfolder" (`demo/111/222`) and share access to it (give access to `…/222`)
- [x] check there's no access to root "folders" and data in them
```

## Open Issues/Regressions/Comments
> In this section, regressions or any new issues that may effect customers can be brought up from the test results. This will be beneficial to the community members as well as anyone working support. This section may also contain any pertenant notes from the release coordinator.
