### ISSUE TITLE
Address unresolved comments from Object Lock changes

### ISSUE THREAD

**Issue by NiaStorj** [storj/edge#461]
### Summary:
Address feedback on code reviews for Object Lock

### Document:
https://docs.google.com/document/d/1Xk5dd7FVAkz3jyUz6XZ4Zn56jEmtEYPmJZ8HN8MMJ2U/edit
```[tasklist]
### Tasks
- [x] https://review.dev.storj.io/c/storj/storj/+/13759
- [x] https://review.dev.storj.io/c/storj/storj/+/13871
- [x] https://review.dev.storj.io/c/storj/storj/+/13872
- [x] https://review.dev.storj.io/c/storj/storj/+/13876
- [x] https://review.dev.storj.io/c/storj/storj/+/13890
- [x] https://review.dev.storj.io/c/storj/storj/+/13878
- [x] https://review.dev.storj.io/c/storj/storj/+/13880
- [x] https://review.dev.storj.io/c/storj/storj/+/13877
```
